version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-clientes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientesdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql_data:
